### ISSUE TITLE
HTML lang tag does not get changed when switching language

### ISSUE THREAD

**Issue by julroy67** [SawyerHood/animal-crossing-catch#14]
**Describe the bug**
When changing language the HTML lang tag does not get changed to the selected language.
For CJK (Chinese, Japanese, Korean) languages, if the HTML lang tag is not set, Chinese variant of some of the characters may be shown instead of the local variant which will feel somewhat out of place for those users.

**To Reproduce**
1. Go to site
2. Change language to Japanese
3. Wrong variant of characters are shown (HTML lang tag is set to "en")

**Expected behavior**
Change the HTML lang tag according to the language is set.

**Screenshots**
Chinese variant:
![image](https://user-images.githubusercontent.com/198724/80949555-2f83df00-8e2f-11ea-9ec0-f5c553af9118.png)

Japanese variant:
![image](https://user-images.githubusercontent.com/198724/80949596-41658200-8e2f-11ea-94b3-997609988588.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 32
 - Browser: Firefox
 - Version: 75

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 10
 - Browser: Chrome
 - Version: 81

**Comment by SawyerHood** [comment]
Thanks for reporting! I just pushed a fix!
