### ISSUE TITLE
K.K. Slider Song List

### ISSUE THREAD

**Issue by KamiCrit** [SawyerHood/animal-crossing-catch#21]
A checklist for the collectable K.K. Slider songs available.

**Comment by erwanlbp** [comment]
That could be cool yeah ! 
The url : https://animalcrossing.fandom.com/wiki/K.K._Slider_song_list_(New_Horizons)
It seems the only infos are the title and the cover. Do you think about some other infos ?

**Comment by erwanlbp** [comment]
#22
