### ISSUE TITLE
Resources are not sorted alphabetically

### ISSUE THREAD

**Issue by erwanlbp** [SawyerHood/animal-crossing-catch#27]
**Describe the bug**
The resources are not sorted alphabetically when not in english.

**Screenshots**
![image](https://user-images.githubusercontent.com/14840425/83422955-94c8f100-a42a-11ea-93f6-7669a414186e.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser : Chrome
- Version Ubuntu 18.04

**Smartphone (please complete the following information):**

- Device: OnePlus 6
- Browser Chrome

**Comment by SawyerHood** [comment]
This should be fixed now
