### ISSUE TITLE
Share collections

### ISSUE THREAD

**Issue by Lysoun** [SawyerHood/animal-crossing-catch#29]
**Is your feature request related to a problem? Please describe.**
I am playing the game with friends and we are helping each other to fill their collections. Right now, the only way to do that is to take several screenshots of the application.

**Describe the solution you'd like**
A way to export the data to share it with friends. It may just be a txt file containing the names of all the items with titles like the ones in the app.

**Comment by SawyerHood** [comment]
Would just a txt file be fine? I could also have it export a custom graphic (png) if that would be better.

**Comment by Lysoun** [comment]
I have no idea which option would be better... With a txt, there is a way to search for an item that you may have among the ones needed by the others but with a picture, you may compare your collection and your friend's more easily.

**Comment by SawyerHood** [comment]
Hey @Lysoun, I just added this to the new hamburger menu. You can copy your caught items into your clipboard. You can also import them back into the app!

![image](https://user-images.githubusercontent.com/2380669/83980211-bca3d300-a8c8-11ea-92be-d92128b52066.png)
