### ISSUE TITLE
Regression: Fossils are not translated anymore

### ISSUE THREAD

**Issue by erwanlbp** [SawyerHood/animal-crossing-catch#31]
**Describe the bug**
It seems the fossiles are not translated anymore (all languages except english) 

**Screenshots**

![Peek 2020-06-08 11-17](https://user-images.githubusercontent.com/14840425/84014157-2af49e00-a97a-11ea-8f4d-6ee83f2bd600.gif)

**Desktop (please complete the following information):**

- OS: **Ubuntu 18.04**
- Browser **Chrome**

**Smartphone (please complete the following information):**

- Device: OnePlus 6
- OS: Android

**Comment by SawyerHood** [comment]
Fixed!
