### ISSUE TITLE
Some strings are not translatable

### ISSUE THREAD

**Issue by javmarina** [SawyerHood/animal-crossing-catch#36]
Some strings in the hamburger icon are not translatable. See here:
![image](https://user-images.githubusercontent.com/2737599/86175239-42f7b180-bb23-11ea-87cd-a6c36d34920c.png)
I think it doesn't make sense to have a mix of English and other languague.

**Comment by SawyerHood** [comment]
Thanks for catching this. Fixed!

**Comment by javmarina** [comment]
"Import" is still not translatable. I fixed it in https://github.com/SawyerHood/animal-crossing-catch/pull/42
