### ISSUE TITLE
Add support for the July update

### ISSUE THREAD

**Issue by SawyerHood** [SawyerHood/animal-crossing-catch#37]
**Is your feature request related to a problem? Please describe.**
I am going to guess that we will have new things that we can collect via diving with the July update. It would be good to add these in its own tab.

**Describe the solution you'd like**
The display should be just like fish

This would be a great feature for someone who would like to contribute!

**Comment by danilo-barboza** [comment]
@SawyerHood Would that cover this issue? https://github.com/SawyerHood/animal-crossing-catch/pull/38
