### ISSUE TITLE
Translations for Sea Creatures

### ISSUE THREAD

**Issue by SawyerHood** [SawyerHood/animal-crossing-catch#39]
@danilo-barboza added sea creatures for us! It would be radical to add support for our other languages.

**Comment by javmarina** [comment]
Count on me for the Spanish translation!

**Comment by arechauchauchau** [comment]
Japanese translations are up as a PR!

**Comment by javmarina** [comment]
Spanish translation is ready (https://github.com/SawyerHood/animal-crossing-catch/pull/42)
