### ISSUE TITLE
Incorrect catch data: Lobster and Spider crab 

### ISSUE THREAD

**Issue by Charkizard** [SawyerHood/animal-crossing-catch#44]
**Describe the bug**
Both the spider crab and lobster creatures are listed as available all year. But in fact, they are only available at certain periods:

Spider crab: March-April (Northern) / September-October (Southern)
Lobster: April-June, December-January (Northern) / October-December, June-July (Southern)

I've been using ac-catch since it's release and I wondered why I had caught everything this month (Northern Hemisphere) besides these two creatures after extensive diving, so I reached out to other websites to clarify their catch periods.

Several sites which list the correct catch duration data:
- https://www.polygon.com/animal-crossing-new-horizons-switch-acnh-guide/2020/7/2/21307259/diving-critters-sea-creatures-critterpedia-list
- https://www.ign.com/wikis/animal-crossing-new-horizons/Sea_Creatures_Guide%3A_Sea_Creature_List%2C_Sell_Price
- https://www.nintendolife.com/guides/animal-crossing-new-horizons-sea-creatures-complete-list-and-price-guide

**To Reproduce**

1. Visit ac-catch.com/
2. Navigate to Sea Creatures tab
3. View spider crab or lobster
4. See incorrect catch duration ("All year")

**Expected behavior**
Both the spider crab and lobster catch data should be updated:

Spider crab: N: "Mar - Apr"; S: "Sep - Oct"
Lobster: N: "Dec - Jan, Apr - Jun"; S: "Jun - Jul, Oct - Dec"

**Screenshots**
https://imgur.com/oMl315h

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Firefox
- Version 78.0.2

**Smartphone (please complete the following information):**

- Device: OnePlus6
- OS: Android
- Browser Firefox
- Version 68.10.1

**Comment by javmarina** [comment]
The way data is retreived is by using a scraper (script that runs periodically and loads data from [here](https://animalcrossing.fandom.com/wiki/Deep-sea_creatures_(New_Horizons))). The data there seems correct, so maybe [the scraper](https://github.com/SawyerHood/animal-crossing-catch/blob/master/scraper/scraper.js) hasn't run yet or it's not working correctly. I think it's the former, because the "Swimming speed" column has been edited recently and the changes don't appear in the https://ac-catch.com/ page.

**Comment by SawyerHood** [comment]
Yeah @javmarina, a contributor added creatures as soon as they were released. I'll scrape again and make sure everything is updated.

**Comment by Charkizard** [comment]
I've just hard refreshed ac-catch and I can validate that re-running the scraper has resolved this issue. Thanks!
