### ISSUE TITLE
Service worker on Safari uses excessive CPU?

### ISSUE THREAD

**Issue by kalidorob** [SawyerHood/animal-crossing-catch#5]
**Describe the bug**
After resumption from 12h sleep, the ac-catch.com service worker pegged a CPU at near 100% on Safari

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.3
 - Browser: Safari 13.0.5 (15608.5.11)

**Comment by SawyerHood** [comment]
I'll dig into this! Thanks for the heads up. I'm using the default create-react-app service worker so I hope this isn't a bug with that 😬

**Comment by SawyerHood** [comment]
I spent a while trying to repro this and wasn't able to get it to reproduce. Closing for now
