### ISSUE TITLE
Feature request: French and Japanese Translations

### ISSUE THREAD

**Issue by julroy67** [SawyerHood/animal-crossing-catch#8]
**Is your feature request related to a problem? Please describe.**
It would be awesome if it were possible to change language on the fly.

**Describe the solution you'd like**
Add a button to switch language.

**Describe alternatives you've considered**
None

**Additional context**
I am French but I play the game in Japanese. When talking with friends, I often have to switch from one language to another (French, English and Japanese) and I don't always remember the names in each language. Most sites don't have multiple languages.

**Comment by SawyerHood** [comment]
Hey @julroy67, thanks to @FlorianReinprecht we have support for multiple languages (just German and English atm). If you would be willing to do a translation, all of the infrastructure is set up!

**Comment by julroy67** [comment]
@SawyerHood Nice, let me add the FR and JP translation! 😄

**Comment by FlorianReinprecht** [comment]
Hey @julroy67 , 
a friend of mine started with a french tanslation. She may not be a native like you, but maybe you can use it as a starting point. 😄

[fr.txt](https://github.com/SawyerHood/animal-crossing-catch/files/4563213/fr.txt)

**Comment by julroy67** [comment]
@FlorianReinprecht Thanks, I'll check that and merge into my version!
