### ISSUE TITLE
Support art collection 

### ISSUE THREAD

**Issue by UzairHaq** [SawyerHood/animal-crossing-catch#9]
**Is your feature request related to a problem? Please describe.**
I would like a way to determine what art I have collected so far from Redd. 

**Describe the solution you'd like**
I would like another tab (similar to Fish, Bugs, Fossils) which supports the art you can collect from Redd.

**Comment by SawyerHood** [comment]
This is top of my list once I get a little more free time!

**Comment by SawyerHood** [comment]
I just pushed this feature, I plan on adding info for the fakes soon
